// Copyright 2022 Diego Palacios (@diepala)
// SPDX-License-Identifier: GPL-2.0

#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x6_3(KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC, KC_LCTL, LALT_T(KC_A), LSFT_T(KC_S), LGUI_T(KC_D), LCTL_T(KC_F), KC_G, LT(3,KC_H), RCTL_T(KC_J), RGUI_T(KC_K), RSFT_T(KC_L), RALT_T(KC_SCLN), KC_QUOT, KC_LSFT, LCTL_T(KC_Z), KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, RCTL_T(KC_SLSH), KC_RSFT, LALT_T(KC_TAB), LT(1,KC_ENT), LT(3,KC_ESC), KC_BTN1, LSFT_T(KC_SPC), LT(2,KC_BSPC)),
	[1] = LAYOUT_split_3x6_3(KC_NO, KC_F9, KC_F10, KC_F11, KC_F12, LGUI(KC_F3), KC_DOT, KC_7, KC_8, KC_9, KC_EQL, KC_NO, KC_NO, KC_F5, KC_F6, KC_F7, KC_F8, LGUI(KC_F2), KC_MINS, KC_4, KC_5, KC_6, KC_PLUS, KC_NO, KC_NO, KC_F1, KC_F2, KC_F3, KC_F4, LGUI(KC_F1), KC_ASTR, KC_1, KC_2, KC_3, KC_SLSH, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_0, KC_DOT, KC_TRNS),
	[2] = LAYOUT_split_3x6_3(KC_NO, KC_QUOT, KC_DQUO, KC_EXLM, KC_ASTR, KC_TILD, KC_NO, KC_UNDS, KC_NO, KC_GRV, KC_PIPE, KC_NO, KC_NO, KC_AT, KC_HASH, KC_DLR, KC_LPRN, KC_RPRN, TO(4), KC_LBRC, KC_RBRC, KC_LCBR, KC_RCBR, KC_NO, KC_NO, KC_NO, KC_PERC, KC_NO, KC_CIRC, KC_BSLS, KC_AMPR, KC_NO, KC_NO, KC_EQL, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[3] = LAYOUT_split_3x6_3(KC_NO, LALT(KC_F4), TO(4), KC_END, KC_BTN3, KC_BTN2, KC_WBAK, LCTL(KC_PGUP), LCTL(KC_PGDN), KC_WFWD, KC_MPRV, KC_NO, KC_NO, KC_HOME, KC_BSPC, KC_DEL, LCTL(KC_RGHT), KC_BTN1, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_NO, KC_NO, LGUI(KC_F1), LGUI(KC_F2), RCS(KC_C), RCS(KC_V), LCTL(KC_LEFT), KC_MNXT, KC_MUTE, KC_VOLD, KC_VOLU, KC_MPLY, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_BTN3, KC_BTN2, KC_TRNS)

};

