#define POINTING_DEVICE_SCLK_PIN F7
#define POINTING_DEVICE_SDIO_PIN F6
#define POINTING_DEVICE_CS_PIN B1

#define POINTING_DEVICE_DEBUG
#define POINTING_DEVICE_ROTATION_270
#define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_INVERT_Y
#define TRACKBALL_DRAGSCROLL_REVERSE_Y

#define DRAGSCROLL_LAYERS 0b10
