
/* keyboard uid */
#define VIAL_KEYBOARD_UID {0xB3, 0x48, 0x8E, 0x0E, 0x05, 0xDB, 0x20, 0xF4}

#define DYNAMIC_KEYMAP_LAYER_COUNT 8

#define VIAL_UNLOCK_COMBO_ROWS { 0, 4 }
#define VIAL_UNLOCK_COMBO_COLS { 4, 4 }

/* trackpoint */
#define PS2_DATA_PIN GP26
#define PS2_CLOCK_PIN GP27
#define PS2_MOUSE_ROTATE 270
#define PS2_DRIVER vendor
#define PS2_PIO_USE_PIO1
#define PS2_MOUSE_SCROLL_BTN_MASK 0
#define PS2_MOUSE_SCROLL_LAYER_MASK (1<<3)
#define PS2_MOUSE_SCROLL_DIVISOR_H 3
#define PS2_MOUSE_SCROLL_DIVISOR_V 3
