#define POINTING_DEVICE_SCLK_PIN GP2
#define POINTING_DEVICE_SDIO_PIN GP0
#define POINTING_DEVICE_CS_PIN GP1

#define POINTING_DEVICE_DEBUG
#define POINTING_DEVICE_INVERT_Y
#define TRACKBALL_DRAGSCROLL_REVERSE_Y

#define DRAGSCROLL_LAYER 1
#define DIRECTION_LAYER 2
